server:
  http:
    addr: 0.0.0.0:8000
    timeout: 600s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
prometheus:
  address: http://llm207:31601
  timeout: 1m
node_selectors:
  Ascend: ascend=on
  DCU: dcu=on
  MLU: mlu=on
  NVIDIA: gpu=on
enable_metrics_cache: true